/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const currentLocale = process.env.DOCUSAURUS_CURRENT_LOCALE ?? 'zh-CN';
const isEnglish = currentLocale === 'en';

const categoryCopy = {
  general: {
    'zh-CN': {
      label: '开始',
      title: '开始使用知识库',
      description: '了解知识库的定位、内容范围与阅读方式。',
    },
    en: {
      label: 'Start here',
      title: 'Start with the knowledge base',
      description:
        'Learn the purpose, scope, and navigation model of the knowledge base.',
    },
  },
  guides: {
    'zh-CN': {
      label: '指南',
      title: '实践指南',
      description: '按步骤完成知识编写、校验与发布。',
    },
    en: {
      label: 'Guides',
      title: 'Practical guides',
      description:
        'Follow step-by-step workflows for writing, validating, and publishing knowledge.',
    },
  },
  reference: {
    'zh-CN': {
      label: '参考',
      title: '发布参考',
      description: '查询内容字段、目录、链接与资源约定。',
    },
    en: {
      label: 'Reference',
      title: 'Publishing reference',
      description:
        'Look up content fields, directories, links, and asset conventions.',
    },
  },
} as const;

const categoryItems = Object.entries(categoryCopy).map(
  ([directory, translations]) => {
    const copy = translations[isEnglish ? 'en' : 'zh-CN'];
    return {
      type: 'category' as const,
      label: copy.label,
      link: {
        type: 'generated-index' as const,
        slug: `/category/${directory}`,
        title: copy.title,
        description: copy.description,
      },
      items: [
        {
          type: 'autogenerated' as const,
          dirName: `knowledge-base/${directory}`,
        },
      ],
    };
  },
);

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: isEnglish ? 'Knowledge Base' : '知识库',
      link: {
        type: 'doc',
        id: 'knowledge-base/general/knowledge-base',
      },
      collapsed: false,
      items: categoryItems,
    },
  ],
};

export default sidebars;
